
backend:
  name: github
  repo: stuible/portfolio

media_folder: "static/images/uploads"
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/posts"
    publish_mode: editorial_workflow
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Icon", name: "icon", widget: "image", required: false}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
  - label: "Custom Sections"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: "Profile Image", name: "image", widget: "image", required: false, tagname: ""}
          - {label: Bio, name: bio, widget: text}
          - label: "Technologies"
            name: "technologies"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: "Image", name: "image", widget: "image", required: false, default: "/uploads/rectangle-copy-23.svg"}
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - label: "Technology Used"
                name: "technology"
                widget: "list"
                fields:
                  - {label: Name, name: name, widget: string}
      - label: "Resume"
        name: "resume"
        file: "content/pages/resume.yml"
        fields:
          - {label: Title, name: title, widget: string}
      - label: "Footer"
        name: "footer"
        file: "content/pages/footer.yml"
        fields:
          - {label: Message, name: message, widget: string}