
backend:
  name: github
  repo: stuible/portfolio

media_folder: "static/images/uploads"
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/posts"
    publish_mode: editorial_workflow
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
  - label: "Custom Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Bio, name: bio, widget: text}
      - label: "Resume"
        name: "resume"
        file: "content/pages/resume.yml"
        fields:
          - {label: Title, name: title, widget: string}