backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow

# media_folder: static/img
# public_folder: /img

collections:
  - name: "piece"
    label: "Portfolio Piece"
    slug: "{{title}}" # this will be filename
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}